(async()=>{
const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const els=new Map();
const element=()=>({textContent:'',innerHTML:'',value:'',style:{},classList:{toggle(){}},close(){},showModal(){}});
const sandbox={console,Intl,Date,Number,String,JSON,Map,Set,Error,structuredClone,crypto:require('node:crypto').webcrypto,setTimeout(){},alert(){},localStorage:{getItem(){return null},setItem(k,v){this.saved=v}},FormData:class{constructor(form){return Object.entries(form.values)}},document:{querySelector(s){if(!els.has(s))els.set(s,element());return els.get(s)},querySelectorAll(){return []},addEventListener(){}}};
sandbox.cloudStore={async save(before,next){sandbox.localStorage.saved=JSON.stringify(next);return structuredClone(next)}};
vm.createContext(sandbox);
vm.runInContext(readFileSync(__dirname+'/../dist/app.js','utf8'),sandbox);
const run=s=>vm.runInContext(s,sandbox);
const submit=values=>els.get('#form').onsubmit({preventDefault(){},target:{values}});
run("openForm('customer')");await submit({name:'Pembeli Uji',city:'Bandung',payment_type:'credit',term_days:'30',credit_limit:'100000',phone:'',address:''});
assert.equal(run('db.customers.length'),1);
const cid=run('db.customers[0].id');
run("openForm('debt')");await submit({customer_id:cid,amount:'100000',date:'2026-01-01',due_date:'2026-01-31',note:'Uji'});
assert.equal(run('balance(db.debts[0])'),100000);
assert.equal(run('status(db.debts[0])'),'late');
const did=run('db.debts[0].id');
run("openForm('payment')");await submit({debt_id:did,amount:'40000',date:'2026-01-02',method:'Tunai',note:''});
assert.equal(run('balance(db.debts[0])'),60000);
run("openForm('payment')");await submit({debt_id:did,amount:'60001',date:'2026-01-03',method:'Tunai',note:''});
assert.equal(run('db.payments.length'),1);
assert.match(els.get('#error').textContent,/melebihi/);
await submit({debt_id:did,amount:'60000',date:'2026-01-03',method:'Tunai',note:''});
assert.equal(run('balance(db.debts[0])'),0);assert.equal(run('status(db.debts[0])'),'paid');
assert.equal(JSON.parse(sandbox.localStorage.saved).payments.length,2);
run("openForm('debt')");await submit({customer_id:cid,amount:'100',date:'2026-01-03',due_date:'2026-01-01',note:''});
assert.equal(run('db.debts.length'),1);assert.match(els.get('#error').textContent,/Jatuh tempo/);
assert.equal(run("esc('<script>')"),'&lt;script&gt;');
console.log('PASS: customer creation, debt creation, overdue status, partial payment, overpayment rejection, settlement, persistence, date validation, HTML escaping.');

run("openForm('debt')");await submit({customer_id:cid,amount:'100001',date:'2026-01-01',due_date:'2026-01-31',note:''});
assert.equal(run('db.debts.length'),1);assert.match(els.get('#error').textContent,/limit/);
assert.equal(run("dueDate('2026-01-31',30)"),'2026-03-02');
run("openForm('customer')");await submit({name:'Tunai',city:'Solo',payment_type:'cash',phone:'',address:''});
const cashid=run('db.customers[1].id');
run("openForm('debt')");await submit({customer_id:cashid,amount:'100',date:'2026-01-01',due_date:'2026-01-01',note:''});
assert.equal(run('db.debts.length'),1);assert.match(els.get('#error').textContent,/bayar di tempat/);
assert.equal(run('maturity(db.customers[0].id).amount'),0);
console.log('PASS: credit limit, cash-only debt rejection, term date calculation, settled maturity.');
sandbox.setInterval=()=>{};
vm.runInContext(readFileSync(__dirname+'/../dist/orders.js','utf8'),sandbox);
const shipment={destination_address:'Jalan Melati 10, Bandung',recipient_name:'Penerima Uji',recipient_phone:'0811111111',delivery_code:'SJ-001',shipping_date:run('today()'),estimated_arrival:run('today()'),driver_name:'Supir Uji',driver_phone:'0800000000',vehicle_number:'B 1234 MJ',comment:'Barang uji <aman>'};
sandbox.shipment=shipment;
await run('storeOrder(shipment)');
assert.equal(run('db.orders.length'),1);
const oid=run('db.orders[0].id');sandbox.oid=oid;
await run("transitionOrder(oid,'transit')");assert.equal(run('db.orders[0].status'),'transit');
await assert.rejects(()=>run("transitionOrder(oid,'cancelled')"),/tidak valid/);
await assert.rejects(()=>run("transitionOrder(oid,'arrived','2020-01-01')"),/Tanggal sampai/);
await run("transitionOrder(oid,'arrived')");assert.equal(run('db.orders[0].status'),'arrived');
assert.equal(run('lateDays(db.orders[0])'),0);
assert.equal(run("lateDays({status:'transit',estimated_arrival:'2026-01-01'},'2026-01-04')"),3);
assert.equal(run("lateDays({status:'arrived',estimated_arrival:'2026-01-01',arrival_date:'2026-01-02'},'2026-02-01')"),1);
assert.equal(run("lateDays({status:'cancelled',estimated_arrival:'2026-01-01'},'2026-02-01')"),0);
await assert.rejects(()=>run("storeOrder({...shipment,estimated_arrival:'2020-01-01'})"),/Estimasi tiba/);
await run('storeOrder(shipment)');await run("transitionOrder(db.orders[1].id,'cancelled')");
assert.equal(run('db.orders[1].status'),'cancelled');assert.equal(run('db.orders.length'),2);
run("page='orders';render()");assert.match(els.get('#view').innerHTML,/Schedule Pengiriman/);
assert.match(els.get('#view').innerHTML,/Riwayat dibatalkan/);
assert.equal(JSON.parse(sandbox.localStorage.saved).orders.length,2);
console.log('PASS: shipment creation, transitions, cancellation history, arrival validation, late days, persistence, and order rendering.');

assert.match(run('orderCard(db.orders[0])'),/Jalan Melati/);
assert.ok(!run('orderCard(db.orders[0])').includes('Supir Uji'));
run('orderDetail(db.orders[0].id)');assert.match(els.get('#fields').innerHTML,/SJ-001/);assert.match(els.get('#fields').innerHTML,/Penerima Uji/);
console.log('PASS: compact shipping row and complete detail.');
assert.equal(run('transactionSummary(db.customers[0].id).total'),100000);
assert.equal(run("transactionSummary(db.customers[0].id,'2026-01-01','2026-01-01').count"),1);
assert.equal(run("transactionSummary(db.customers[0].id,'2026-01-02','2026-01-31').total"),0);
run("page='customers';render()");assert.match(els.get('#rows').innerHTML,/TOTAL TRANSAKSI/);assert.match(els.get('#rows').innerHTML,/<th>ID<\/th>/);
run('openForm("customer",db.customers[0].id)');await submit({registered_id:'00012',name:'Pembeli Uji',city:'Bandung',payment_type:'credit',term_days:'30',credit_limit:'100000',phone:'',address:''});
assert.equal(run('db.customers[0].registered_id'),'00012');
run('openForm("customer")');await submit({registered_id:'00012',name:'Duplikat',city:'Bandung',payment_type:'cash',phone:'',address:''});
assert.match(els.get('#error').textContent,/sudah digunakan/);
console.log('PASS: historical totals include settled transactions, inclusive date ranges, registered IDs and duplicate rejection.');
run("page='dashboard';query='';filter='all';render()");
assert.ok(!els.get('#rows').innerHTML.includes('Lihat detail'));
assert.equal(run('debtDistribution().total'),0);
run("db.debts.push({id:'chart-test',customer_id:db.customers[0].id,amount:30000,date:today(),due_date:today(),note:'Chart test'})");
assert.equal(run('debtDistribution().total'),30000);
assert.equal(run('debtDistribution().slices.length'),1);
run('render()');assert.match(els.get('#rows').innerHTML,/Chart test/);
assert.match(run('debtChart()'),/100%/);
run("page='debts';render()");assert.match(els.get('#rows').innerHTML,/Lunas/);
console.log('PASS: dashboard excludes settled bills, history retains them, chart totals use outstanding balances.');
run("page='payments';query='';transactionFrom='2026-01-02';transactionTo='2026-01-02';render()");
assert.match(els.get('#view').innerHTML,/range-toggle/);
assert.match(els.get('#rows').innerHTML,/40\.000/);
assert.ok(!els.get('#rows').innerHTML.includes('60.000'));
run("transactionFrom='';transactionTo='';renderRows()");
assert.match(els.get('#rows').innerHTML,/60\.000/);
console.log('PASS: payment date range includes boundary date and All data restores full history.');

})().catch(error=>{console.error(error);process.exitCode=1});
